# Generated by Django 6.0.6 on 2026-06-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='budget_max_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='budget_min_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_areas',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'System Administrator'), ('sales_manager', 'Sales Manager'), ('property_manager', 'Property Manager'), ('valuation_manager', 'Valuation & Appraisal Manager'), ('accountant', 'Accountant / Finance Officer'), ('agent', 'Real Estate Agent / Realtor'), ('landlord', 'Seller / Landlord'), ('tenant', 'Tenant / Renter'), ('buyer', 'Buyer / Prospective Renter'), ('manager', 'General Manager'), ('owner', 'Property Owner')], default='agent', max_length=25),
        ),
    ]
