# Generated by Django 6.0.6 on 2026-06-23 03:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0001_initial'),
        ('leases', '0003_initial'),
        ('properties', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('routine', 'Routine Inspection'), ('move_in', 'Move-In Inspection'), ('move_out', 'Move-Out Inspection'), ('annual', 'Annual Inspection'), ('pre_sale', 'Pre-Sale Inspection'), ('maintenance', 'Maintenance Follow-Up'), ('compliance', 'Compliance / Insurance')], default='routine', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('tenant_notified', models.BooleanField(default=False)),
                ('tenant_present', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='scheduled', max_length=15)),
                ('overall_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('na', 'N/A')], default='na', max_length=15)),
                ('report_summary', models.TextField(blank=True)),
                ('action_required', models.BooleanField(default=False)),
                ('action_description', models.TextField(blank=True)),
                ('next_inspection_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_inspections', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='leases.lease')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='properties.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='properties.unit')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='LandlordDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.PositiveIntegerField(help_text='1–12')),
                ('period_year', models.PositiveIntegerField()),
                ('gross_rent_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('agent_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('10'), help_text='% of gross rent', max_digits=5)),
                ('agent_commission_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('15'), help_text='ZIMRA VAT on commission %', max_digits=5)),
                ('vat_on_commission_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('other_deductions_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('other_deductions_description', models.CharField(blank=True, max_length=300)),
                ('repairs_deducted_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('net_to_landlord_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('net_to_landlord_zig', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=15)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='currency.exchangerate')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_disbursements', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='properties.property')),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('property', 'period_month', 'period_year')},
            },
        ),
    ]
