# Generated by Django 6.0.6 on 2026-08-02 08:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlorddisbursement',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.5'), help_text='ZIMRA VAT on commission %', max_digits=5),
        ),
    ]
