# Generated by Django 6.0.6 on 2026-08-06 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0003_bulkpaymentbatch_bulkpaymentitem'),
        ('valuation', '0002_alter_valuation_method_salescomparablesdb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinspection',
            name='condition_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Automated 0-100 score computed from checklist items', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='propertyinspection',
            name='valuation',
            field=models.ForeignKey(blank=True, help_text='Link this inspection into a valuation, feeding its condition score into the AVM', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='valuation.valuation'),
        ),
        migrations.CreateModel(
            name='InspectionChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('structural', 'Structural'), ('roofing', 'Roofing'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('hvac', 'HVAC'), ('interior', 'Interior Finishes'), ('exterior', 'Exterior / Facade'), ('safety', 'Safety & Compliance'), ('appliances', 'Appliances & Fixtures'), ('grounds', 'Grounds / Landscaping'), ('other', 'Other')], default='other', max_length=20)),
                ('item_name', models.CharField(max_length=200)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('na', 'N/A')], default='na', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('requires_action', models.BooleanField(default=False)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='lettings.propertyinspection')),
            ],
            options={
                'ordering': ['category', 'item_name'],
            },
        ),
    ]
