# Generated by Django 6.0.6 on 2026-08-12 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0004_propertyinspection_condition_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinspection',
            name='electricity_reading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='propertyinspection',
            name='inspector_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyinspection',
            name='tenant_acknowledged',
            field=models.BooleanField(default=False, help_text='Tenant has reviewed and agreed with the recorded condition'),
        ),
        migrations.AddField(
            model_name='propertyinspection',
            name='tenant_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyinspection',
            name='water_reading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inspection_photos/')),
                ('photo_type', models.CharField(choices=[('before', 'Before'), ('after', 'After'), ('general', 'General')], default='general', max_length=10)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='lettings.inspectionchecklistitem')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='lettings.propertyinspection')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
