# Generated by Django 6.0.6 on 2026-06-22 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('usd_to_zig', models.DecimalField(decimal_places=4, help_text='How many ZiG per 1 USD', max_digits=14)),
                ('source', models.CharField(choices=[('rbz', 'RBZ Official Rate'), ('interbank', 'Interbank Rate'), ('parallel', 'Parallel Market Rate'), ('manual', 'Manual Entry')], default='rbz', max_length=15)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
