# Generated by Django 6.0.6 on 2026-06-22 16:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='latefeerule',
            name='fee_type',
            field=models.CharField(choices=[('flat', 'Flat Amount'), ('percent', 'Percentage')], default='flat', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('check', 'Check'), ('cash', 'Cash'), ('online', 'Online Portal'), ('ach', 'ACH')], default='bank_transfer', max_length=20),
        ),
    ]
