# Generated by Django 6.0.6 on 2026-08-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_invoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer / RTGS'), ('ecocash', 'EcoCash'), ('zipit', 'Zipit'), ('swipe', 'Swipe (POS)'), ('cash', 'Cash (USD)'), ('cheque', 'Cheque'), ('online', 'Online Portal')], default='bank_transfer', max_length=20),
        ),
    ]
