# Generated by Django 6.0.6 on 2026-08-06 15:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
        ('leases', '0003_initial'),
        ('rent', '0004_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('ZiG', 'ZiG')], default='USD', help_text='Currency the tenant is billed in', max_length=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='exchange_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='currency.exchangerate'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount_zig',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='total_amount converted to ZiG at time of invoicing', max_digits=14),
        ),
        migrations.CreateModel(
            name='RecurringInvoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=10)),
                ('billing_day', models.PositiveSmallIntegerField(default=1, help_text='Day of month invoices are generated (1-28)')),
                ('due_in_days', models.PositiveSmallIntegerField(default=5, help_text='Days after generation the invoice is due')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('ZiG', 'ZiG')], default='USD', max_length=5)),
                ('other_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('auto_generate_disbursement', models.BooleanField(default=False, help_text='When an invoice from this profile is paid in full, auto-run the landlord disbursement calculation for that period')),
                ('is_active', models.BooleanField(default=True)),
                ('next_generation_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_profiles', to='leases.lease')),
            ],
            options={
                'ordering': ['next_generation_date'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='recurring_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_invoices', to='rent.recurringinvoiceprofile'),
        ),
    ]
