# Generated by Django 6.0.6 on 2026-08-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='category_type',
            field=models.CharField(choices=[('insurance', 'Insurance (Old Mutual / ZB / Zimnat)'), ('rates', 'City Council Rates'), ('utilities', 'Utilities (ZESA / ZINWA)'), ('mortgage', 'Mortgage / Bond Repayment'), ('management', 'Management Fees'), ('repairs', 'Repairs & Maintenance'), ('landscaping', 'Landscaping'), ('council_levy', 'Council Levy / ZINARA'), ('advertising', 'Advertising'), ('legal', 'Legal & Professional'), ('accounting', 'Accounting / Audit'), ('supplies', 'Supplies'), ('security', 'Security (Securico / G4S)'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
