# Generated by Django 6.0.6 on 2026-08-06 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0003_alter_contact_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('id_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('company_reg', 'Company Registration')], default='national_id', max_length=20)),
                ('id_number', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(default='Zimbabwe', max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('source_of_funds', models.TextField(blank=True)),
                ('is_pep', models.BooleanField(default=False, verbose_name='Politically Exposed Person')),
                ('pep_details', models.TextField(blank=True)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='kyc_documents/id/')),
                ('proof_of_address', models.FileField(blank=True, null=True, upload_to='kyc_documents/address/')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Re-verification due date (KYC records go stale)', null=True)),
                ('risk_score', models.PositiveSmallIntegerField(default=0, help_text='0-100, higher = riskier')),
                ('risk_rating', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_profile', to='sales.contact')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Profile',
                'verbose_name_plural': 'KYC Profiles',
                'ordering': ['-risk_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoredTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('rent_payment', 'Rent Payment'), ('trust_deposit', 'Trust Account Deposit'), ('property_sale', 'Property Sale'), ('reservation_token', 'Reservation Token / Deposit'), ('landlord_disbursement', 'Landlord Disbursement'), ('other', 'Other')], default='other', max_length=25)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=300)),
                ('flags', models.JSONField(default=list, help_text='List of triggered rule codes, e.g. ["LARGE_CASH"]')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('status', models.CharField(choices=[('flagged', 'Flagged — Pending Review'), ('cleared', 'Cleared'), ('reported', 'Reported to FIU (goAML)')], default='flagged', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('goaml_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aml_reviews', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='aml.kycprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
