# Generated by Django 6.0.6 on 2026-08-10 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=300)),
                ('aliases', models.TextField(blank=True, help_text='One alias per line')),
                ('list_source', models.CharField(choices=[('ofac_sdn', 'OFAC SDN List'), ('un_consolidated', 'UN Security Council Consolidated List'), ('local_pep', 'Local PEP List'), ('other', 'Other')], default='other', max_length=20)),
                ('entry_type', models.CharField(choices=[('sanction', 'Sanctioned Entity/Individual'), ('pep', 'Politically Exposed Person'), ('other', 'Other')], default='sanction', max_length=10)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Watchlist Entries',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='entity_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('trust', 'Trust'), ('company', 'Company / Corporate')], default='individual', max_length=10),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Company/trust registration number — required for entity_type != individual', max_length=100),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='residency_status',
            field=models.CharField(choices=[('resident', 'Resident'), ('non_resident', 'Non-Resident')], default='resident', help_text='Non-resident property buyers are a recognized FATF risk factor', max_length=15),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='watchlist_matches',
            field=models.JSONField(blank=True, default=list, help_text='Result of the most recent sanctions/PEP watchlist screening — list of {entry_id, matched_name, score, list_source, entry_type}'),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='watchlist_screened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycprofile',
            name='full_name',
            field=models.CharField(help_text='Individual name, or registered trust/company name', max_length=200),
        ),
        migrations.AlterField(
            model_name='monitoredtransaction',
            name='source_type',
            field=models.CharField(choices=[('rent_payment', 'Rent Payment'), ('trust_deposit', 'Trust Account Deposit'), ('property_sale', 'Property Sale'), ('reservation_token', 'Reservation Token / Deposit'), ('landlord_disbursement', 'Landlord Disbursement'), ('buyer_offer', 'Buyer Offer (pre-sale screening)'), ('other', 'Other')], default='other', max_length=25),
        ),
        migrations.CreateModel(
            name='BeneficialOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('id_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('company_reg', 'Company Registration')], default='national_id', max_length=20)),
                ('id_number', models.CharField(max_length=100)),
                ('nationality', models.CharField(default='Zimbabwe', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, help_text='% ultimate beneficial ownership/control — goAML requires this per owner', max_digits=5)),
                ('is_pep', models.BooleanField(default=False, verbose_name='Politically Exposed Person')),
                ('watchlist_matches', models.JSONField(blank=True, default=list, help_text="Result of screening this beneficial owner's own name against the watchlist")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kyc_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficial_owners', to='aml.kycprofile')),
            ],
            options={
                'ordering': ['-ownership_percentage'],
            },
        ),
    ]
