# Generated by Django 6.0.6 on 2026-06-22 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('deed', 'Title Deed'), ('blueprint', 'Blueprint / Site Plan'), ('floor_plan', 'Floor Plan'), ('valuation', 'Valuation Report'), ('insurance', 'Insurance Certificate'), ('rates_clearance', 'Rates Clearance'), ('inspection', 'Inspection Report'), ('fire_cert', 'Fire Safety Certificate'), ('lease_doc', 'Signed Lease'), ('sale_agreement', 'Offer to Purchase'), ('photo', 'Property Photo'), ('virtual_tour', 'Virtual Tour / Video'), ('brochure', 'Marketing Brochure'), ('ecd', 'Environmental Compliance'), ('other', 'Other')], default='other', max_length=30)),
                ('file', models.FileField(upload_to='property_documents/')),
                ('is_confidential', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('file_size_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_documents', to='properties.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_documents', to='properties.unit')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['property', 'document_type', '-created_at'],
            },
        ),
    ]
