# Generated by Django 6.0.6 on 2026-08-12 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField(help_text='Use {{name}} or {{email}} for per-recipient values')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='Set when the recipient was picked from registered users', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='Set when the recipient was picked from registered users', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_sms', to=settings.AUTH_USER_MODEL),
        ),
    ]
