# Generated by Django 6.0.6 on 2026-08-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_emailtemplate_emailmessage_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(help_text='Use {{name}}, {{email}} or {{due_date}} for per-recipient values'),
        ),
    ]
