# Generated by Django 6.0.6 on 2026-06-22 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('median_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('avg_price_per_sqft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_sales', models.PositiveIntegerField()),
                ('avg_days_on_market', models.PositiveIntegerField()),
                ('price_change_pct', models.DecimalField(blank=True, decimal_places=2, help_text='% change from prior period', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['area', '-period_start'],
            },
        ),
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('avm', 'Automated Valuation Model'), ('cma', 'Comparative Market Analysis'), ('appraisal', 'Professional Appraisal'), ('broker_opinion', 'Broker Price Opinion')], default='avm', max_length=20)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('low_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('high_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='0-100 confidence percentage', max_digits=5, null=True)),
                ('valuation_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('report', models.FileField(blank=True, null=True, upload_to='valuations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuations', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='properties.property')),
            ],
            options={
                'ordering': ['-valuation_date'],
            },
        ),
        migrations.CreateModel(
            name='Comparable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sale_date', models.DateField()),
                ('square_feet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=4)),
                ('price_per_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_miles', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('adjustments', models.DecimalField(decimal_places=2, default=0, help_text='Positive/negative price adjustments', max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('valuation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparables', to='valuation.valuation')),
            ],
        ),
    ]
