# Generated by Django 6.0.6 on 2026-06-23 03:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuation',
            name='method',
            field=models.CharField(choices=[('avm', 'Automated Valuation Model'), ('cma', 'Comparable Sales Method'), ('investment', 'Investment Approach'), ('cost', 'Cost Approach'), ('appraisal', 'Full Professional Appraisal'), ('broker_opinion', 'Broker Price Opinion')], default='avm', max_length=20),
        ),
        migrations.CreateModel(
            name='SalesComparablesDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('suburb', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('land', 'Land / Stand'), ('agricultural', 'Agricultural'), ('mixed', 'Mixed Use')], max_length=20)),
                ('tenure', models.CharField(choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold'), ('state_land', 'State Land (99yr)'), ('sectional_title', 'Sectional Title'), ('other', 'Other')], default='freehold', max_length=20)),
                ('land_size_sqm', models.DecimalField(decimal_places=2, help_text='Stand/land size in square metres', max_digits=12)),
                ('floor_area_sqm', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Gross floor area / improvements in sqm', max_digits=10)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('garages', models.PositiveIntegerField(default=0)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=15)),
                ('sale_price_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sale_date', models.DateField()),
                ('days_on_market', models.PositiveIntegerField(blank=True, null=True)),
                ('price_per_sqm_land_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_sqm_floor_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('deeds_registry', 'Deeds Registry'), ('agent_confirmed', 'Agent Confirmed'), ('newspaper', 'Herald / NewsDay'), ('own_sale', 'In-House Sale'), ('other_valuer', 'Other Valuer'), ('other', 'Other')], default='agent_confirmed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_comparables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Comparable',
                'verbose_name_plural': 'Sales Comparables Database',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='ValuationMethodology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('comparable_sales', 'Comparable Sales Method'), ('investment', 'Investment Approach (Income Capitalisation)'), ('cost', 'Cost Approach (Depreciated Replacement Cost)')], max_length=25)),
                ('calculated_value_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('weight_pct', models.DecimalField(decimal_places=2, default=Decimal('100'), help_text='Weight assigned to this method in final value', max_digits=5)),
                ('inputs', models.JSONField(default=dict, help_text='Method-specific inputs stored as JSON')),
                ('working_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valuation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methodologies', to='valuation.valuation')),
            ],
        ),
    ]
