# Generated by Django 6.0.6 on 2026-06-22 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_initial'),
        ('sales', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('deal_type', models.CharField(choices=[('sale', 'Sale'), ('lease', 'Lease'), ('all', 'All')], default='all', max_length=10)),
                ('color', models.CharField(default='#3b82f6', max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_won', models.BooleanField(default=False)),
                ('is_lost', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['deal_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('campaign_type', models.CharField(choices=[('whatsapp', 'WhatsApp Blast'), ('email', 'Email'), ('sms', 'SMS')], default='whatsapp', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('message_body', models.TextField()),
                ('target_statuses', models.JSONField(default=list)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('website', 'Website'), ('referral', 'Referral'), ('herald', 'Herald / Newspaper'), ('social', 'Social Media'), ('walk_in', 'Walk-In'), ('phone', 'Phone Call'), ('classifieds', 'Classifieds ZW'), ('signage', 'Property Signage'), ('other', 'Other')], default='whatsapp', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('site_visit', 'Site Visit'), ('negotiating', 'Negotiating'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20)),
                ('deal_type', models.CharField(choices=[('sale', 'Purchase'), ('lease', 'Rental'), ('both', 'Purchase or Rental')], default='sale', max_length=10)),
                ('preferred_location', models.CharField(blank=True, max_length=200)),
                ('budget_min_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('budget_max_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('bedrooms_wanted', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('lost_reason', models.CharField(blank=True, max_length=300)),
                ('next_followup', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('property_interest', models.ManyToManyField(blank=True, related_name='interested_leads', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('call', 'Phone Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS'), ('site_visit', 'Site Visit'), ('meeting', 'Office Meeting'), ('note', 'Note')], default='call', max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='outbound', max_length=10)),
                ('summary', models.TextField()),
                ('outcome', models.CharField(blank=True, choices=[('interested', 'Interested'), ('followup', 'Follow-up Needed'), ('not_interested', 'Not Interested'), ('deal_progressed', 'Deal Progressed'), ('no_answer', 'No Answer'), ('other', 'Other')], max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='sales.contact')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='properties.property')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_type', models.CharField(choices=[('sale', 'Sale'), ('lease', 'Lease')], default='sale', max_length=10)),
                ('expected_value_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('probability', models.PositiveIntegerField(default=20)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='crm.lead')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='properties.property')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.pipelinestage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
