# Generated by Django 6.0.6 on 2026-08-07 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('sales', '0004_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contact',
            field=models.OneToOneField(blank=True, help_text='Set once this lead is converted into a sales Contact, so the same person is never re-typed from scratch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='sales.contact'),
        ),
    ]
