# Generated by Django 6.0.6 on 2026-08-07 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_lead_contact'),
        ('sales', '0004_contact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Set once this lead is converted into (or matched against) a sales Contact, so the same person is never re-typed from scratch — multiple leads (e.g. repeat inquiries) can point at the same contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to='sales.contact'),
        ),
    ]
