# Generated by Django 6.0.6 on 2026-06-22 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_initial'),
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreventiveSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('hvac', 'HVAC / Air Conditioning'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('structural', 'Structural'), ('fire_safety', 'Fire Safety'), ('borehole', 'Borehole / Water'), ('solar', 'Solar / Generator'), ('lifts', 'Lifts / Elevators'), ('landscaping', 'Landscaping'), ('pest_control', 'Pest Control'), ('security', 'Security Systems'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannual', 'Bi-Annual'), ('annual', 'Annual'), ('custom', 'Custom (days)')], default='annual', max_length=15)),
                ('interval_days', models.PositiveIntegerField(blank=True, help_text='Only for custom frequency', null=True)),
                ('last_completed', models.DateField(blank=True, null=True)),
                ('next_due', models.DateField(blank=True, null=True)),
                ('estimated_cost_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_create_work_order', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preventive_schedules', to='properties.property')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preventive_schedules', to='maintenance.vendor')),
            ],
            options={
                'ordering': ['next_due', 'property'],
            },
        ),
    ]
