# Generated by Django 6.0.6 on 2026-08-06 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_preventiveschedule'),
        ('properties', '0003_alter_property_country_alter_property_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_contractors', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, help_text="Leave blank to approve for all of this landlord's properties", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_contractors', to='properties.property')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_approvals', to='maintenance.vendor')),
            ],
            options={
                'ordering': ['-approved_at'],
                'unique_together': {('landlord', 'vendor', 'property')},
            },
        ),
    ]
