# Generated by Django 6.0.6 on 2026-06-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('renewal_pending', 'Renewal Pending')], default='draft', max_length=20)),
                ('custom_terms', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='leases/')),
                ('signed_by_tenant', models.BooleanField(default=False)),
                ('signed_by_landlord', models.BooleanField(default=False)),
                ('tenant_signed_at', models.DateTimeField(blank=True, null=True)),
                ('landlord_signed_at', models.DateTimeField(blank=True, null=True)),
                ('renewal_reminder_days', models.PositiveIntegerField(default=60)),
                ('auto_renew', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaseClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('payment', 'Payment Terms'), ('maintenance', 'Maintenance'), ('pets', 'Pet Policy'), ('subletting', 'Subletting'), ('termination', 'Termination'), ('utilities', 'Utilities'), ('general', 'General')], default='general', max_length=20)),
                ('content', models.TextField()),
                ('is_standard', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaseRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_start', models.DateField()),
                ('proposed_end', models.DateField()),
                ('proposed_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
