# Generated by Django 6.0.6 on 2026-06-22 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0002_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lease',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='properties.unit'),
        ),
        migrations.AddField(
            model_name='lease',
            name='clauses',
            field=models.ManyToManyField(blank=True, to='leases.leaseclause'),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='leases.lease'),
        ),
    ]
