# Generated by Django 6.0.6 on 2026-08-06 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='next_rent_review_date',
            field=models.DateField(blank=True, help_text='Lease Diary tracks this for rent-review alerts, separate from renewal/expiry', null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='rent_review_frequency_months',
            field=models.PositiveIntegerField(blank=True, help_text='e.g. 12 for an annual rent review; leave blank for one-off', null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='rent_review_reminder_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.CreateModel(
            name='RentReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField()),
                ('old_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_reviews', to='leases.lease')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_reviews_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-review_date'],
            },
        ),
    ]
