# Generated by Django 6.0.6 on 2026-08-12 12:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0004_lease_next_rent_review_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_received', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending — Not Yet Received'), ('held', 'Held'), ('refund_requested', 'Refund Requested'), ('refunded', 'Refunded'), ('forfeited', 'Forfeited')], default='pending', max_length=20)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refund_date', models.DateField(blank=True, null=True)),
                ('refund_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('ecocash', 'EcoCash'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=20)),
                ('refund_reference', models.CharField(blank=True, max_length=100)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_refunds_approved', to=settings.AUTH_USER_MODEL)),
                ('lease', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='leases.lease')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_refunds_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepositDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('damage', 'Property Damage'), ('cleaning', 'Cleaning'), ('outstanding_rent', 'Outstanding Rent'), ('unpaid_utilities', 'Unpaid Utilities'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='deposit_deductions/')),
                ('is_suggested', models.BooleanField(default=False, help_text="Auto-suggested from a move-out inspection's poor-condition items, pending staff confirmation")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_deductions_created', to=settings.AUTH_USER_MODEL)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='leases.securitydeposit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
