# Generated by Django 6.0.6 on 2026-08-12 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0005_securitydeposit_depositdeduction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='co_tenants',
            field=models.ManyToManyField(blank=True, help_text='Additional tenants named on this lease besides the primary tenant', related_name='co_leases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lease',
            name='early_termination_date',
            field=models.DateField(blank=True, help_text='Set when the lease is ended before its original end_date', null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='early_termination_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='notice_period_days',
            field=models.PositiveIntegerField(default=30, help_text='Notice period required from either party to end the tenancy'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('renewal_pending', 'Renewal Pending')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='leases.lease')),
            ],
        ),
    ]
