# Generated by Django 6.0.6 on 2026-06-22 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('sales', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('usage_type', models.CharField(choices=[('quote', 'Property Quote'), ('invoice', 'Rent Invoice'), ('payment_receipt', 'Payment Receipt'), ('lease_expiry', 'Lease Expiry Alert'), ('maintenance', 'Maintenance Update'), ('brochure', 'Property Brochure'), ('lead_response', 'Lead Auto-Response'), ('overdue', 'Overdue Warning'), ('reservation', 'Reservation Confirmation'), ('welcome', 'Welcome'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('sn', 'Shona'), ('nd', 'Ndebele')], default='en', max_length=5)),
                ('body_text', models.TextField(help_text='Use {{1}}, {{2}} for variables. E.g. "Dear {{1}}, your rent of ${{2}} is due {{3}}."')),
                ('variable_labels', models.JSONField(default=list)),
                ('footer_text', models.CharField(blank=True, max_length=200)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(blank=True, max_length=100)),
                ('access_token', models.TextField(blank=True)),
                ('webhook_verify_token', models.CharField(blank=True, max_length=200)),
                ('business_account_id', models.CharField(blank=True, max_length=100)),
                ('display_phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('simulate_mode', models.BooleanField(default=True, help_text='Log messages without calling Meta API')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsApp Configuration',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='outbound', max_length=10)),
                ('contact_phone', models.CharField(max_length=30)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('message_text', models.TextField()),
                ('message_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('simulated', 'Simulated')], default='pending', max_length=15)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='sales.contact')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='crm.lead')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_whatsapp', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='whatsapp_integration.whatsapptemplate')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
