# Generated by Django 6.0.6 on 2026-08-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='body_text',
            field=models.TextField(help_text='Use {{variable_name}} for dynamic values. E.g. "Dear {{name}}, your rent of ${{amount}} is due {{date}}."'),
        ),
    ]
