# Generated by Django 6.0.6 on 2026-06-22 20:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0001_initial'),
        ('leases', '0003_initial'),
        ('properties', '0002_initial'),
        ('sales', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('deal_type', models.CharField(choices=[('sale', 'Sale'), ('lease', 'Lease')], default='sale', max_length=10)),
                ('token_amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('token_currency', models.CharField(choices=[('USD', 'USD'), ('ZiG', 'ZiG')], default='USD', max_length=5)),
                ('token_amount_zig', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('payment_received_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('valid_until', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('active', 'Active'), ('converted', 'Converted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expiry_reminder_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoverChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handover_type', models.CharField(choices=[('move_in', 'Move-In'), ('move_out', 'Move-Out'), ('sale_handover', 'Sale Handover'), ('mid_lease', 'Mid-Lease Inspection')], default='move_in', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Snags Outstanding'), ('signed_off', 'Signed Off')], default='pending', max_length=20)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('tenant_present', models.BooleanField(default=False)),
                ('landlord_present', models.BooleanField(default=False)),
                ('key_handover_date', models.DateField(blank=True, null=True)),
                ('keys_count', models.PositiveIntegerField(default=2)),
                ('electricity_meter_reading', models.CharField(blank=True, max_length=50)),
                ('water_meter_reading', models.CharField(blank=True, max_length=50)),
                ('overall_notes', models.TextField(blank=True)),
                ('signed_off_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers', to='leases.lease')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='properties.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers', to='properties.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoverItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('structural', 'Structural'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('fittings', 'Fittings'), ('appliances', 'Appliances'), ('keys', 'Keys'), ('documents', 'Documents'), ('garden', 'Garden'), ('other', 'Other')], default='structural', max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('condition', models.CharField(choices=[('pass', 'Satisfactory'), ('minor', 'Minor Issue'), ('fail', 'Unsatisfactory / Snag'), ('na', 'N/A')], default='pass', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='handover/')),
                ('estimated_repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.handoverchecklist')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('base_price_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('discount_amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('discount_reason', models.CharField(blank=True, max_length=200)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5)),
                ('stamp_duty_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('registration_fees_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('legal_fees_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('parking_cost_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('other_charges_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('other_charges_description', models.CharField(blank=True, max_length=200)),
                ('subtotal_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('vat_amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_zig', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('deal_type', models.CharField(choices=[('sale', 'Sale'), ('lease', 'Lease')], default='sale', max_length=10)),
                ('valid_days', models.PositiveIntegerField(default=14)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('revised', 'Revised'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='sales.contact')),
                ('exchange_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='currency.exchangerate')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
