# Generated by Django 6.0.6 on 2026-08-02 08:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.5'), max_digits=5),
        ),
    ]
