# Generated by Django 6.0.6 on 2026-08-06 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_bankstatementimport_bankstatementline'),
        ('properties', '0003_alter_property_country_alter_property_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('source_type', models.CharField(choices=[('rent_payment', 'Rent Payment'), ('trust_deposit', 'Trust Account Deposit'), ('reservation_token', 'Reservation Token / Deposit'), ('other', 'Other Incoming Funds')], default='other', max_length=20)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('payer_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('received_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_receipts', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='properties.property')),
            ],
            options={
                'ordering': ['-received_date', '-created_at'],
            },
        ),
    ]
