# Generated by Django 6.0.6 on 2026-08-06 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliation',
            name='import_batch',
            field=models.ForeignKey(blank=True, help_text='Set when this reconciliation was derived from a line-item bank statement import rather than typed in by hand', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations', to='accounting.bankstatementimport'),
        ),
    ]
