# Generated by Django 6.0.6 on 2026-08-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('lease_expiring', 'Lease Expiring'), ('lease_expired', 'Lease Expired'), ('rent_overdue', 'Rent Overdue'), ('payment_received', 'Payment Received'), ('work_order_update', 'Work Order Update'), ('maintenance_complete', 'Maintenance Complete'), ('maintenance_assigned', 'Maintenance Assigned'), ('renewal_proposed', 'Renewal Proposed'), ('rent_statement', 'Rent Statement'), ('rent_review_due', 'Rent Review Due'), ('system', 'System')], default='system', max_length=30),
        ),
    ]
