# Generated by Django 6.0.6 on 2026-06-22 11:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_rate', models.DecimalField(decimal_places=2, help_text='Total % commission', max_digits=5)),
                ('listing_agent_split', models.DecimalField(decimal_places=2, help_text='% split to listing agent', max_digits=5)),
                ('buyer_agent_split', models.DecimalField(decimal_places=2, help_text='% split to buyer agent', max_digits=5)),
                ('broker_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('both', 'Buyer & Seller')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('prospect', 'Prospect'), ('active', 'Active Client'), ('closed', 'Closed'), ('inactive', 'Inactive')], default='lead', max_length=20)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('preferred_areas', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('both', 'Sale or Rent')], default='sale', max_length=10)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('sold', 'Sold'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='active', max_length=20)),
                ('listing_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('mls_number', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('virtual_tour_url', models.URLField(blank=True)),
                ('open_house_date', models.DateTimeField(blank=True, null=True)),
                ('days_on_market', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('earnest_money', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('financing_contingency', models.BooleanField(default=True)),
                ('inspection_contingency', models.BooleanField(default=True)),
                ('appraisal_contingency', models.BooleanField(default=True)),
                ('closing_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('countered', 'Countered'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='submitted', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('counter_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('closing_date', models.DateField()),
                ('total_commission', models.DecimalField(decimal_places=2, max_digits=14)),
                ('listing_agent_commission', models.DecimalField(decimal_places=2, max_digits=14)),
                ('buyer_agent_commission', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
