# Generated by Django 6.0.6 on 2026-08-07 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_contact_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Set once this contact registers a platform account (buyer/tenant/landlord login), so KYC, portal activity, and this CRM record all point at the same person instead of duplicating them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
